### ISSUE TITLE
Callout box component

### ISSUE THREAD

**Issue by jcalcaben** [jcalcaben/gatsby-doc-site#31]
Create an equivalent to the `bs-callout` boxes in devdocs.
These will essentially be inline dialog boxes with different colors and icons to indicate purpose:

- info (blue)
- tip (green)
- warning (yellow)
- error/beware (red)

See: https://spectrum.adobe.com/page/dialog/

**Comment by sirugh** [comment]
Example: https://magento.github.io/pwa-studio/venia-pwa-concept/setup/
